### ISSUE TITLE
Just need a lil assistance, my videos arent playing on the repo i forked

### ISSUE THREAD

**Issue by InstaTechHD** [Luckyhv/aniplay#14]
Would it be possible for me to get a little assistance pls?

**Comment by Tohjuler** [comment]
Can you describe it a bit more, like is there any error (web console, logs)
Maby screenshot.

**Comment by Tohjuler** [comment]
It seems like it can't connect to the consumet api.

**Comment by Tohjuler** [comment]
My mistake, it is a core error ```Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at https://jiraiya.vercel.app/api/source/151807. (Reason: CORS preflight response did not succeed). Status code: 405.```
I think it is because of the NEXT_PUBLIC_PRODUCTION_URL not matching the current url.

**Comment by Tohjuler** [comment]
There must be some misconfiguration someware, because the site at https://bruhmakima-rho.vercel.app is trying to use the api at https://jiraiya.vercel.app.

**Comment by Tohjuler** [comment]
You can try to remove the NEXT_PUBLIC_PRODUCTION_URL and NEXT_PUBLIC_DEV_URL from the env, then the site will use the current url.

**Comment by Luckyhv** [comment]
Send me the link i will check it

**Comment by Luckyhv** [comment]
Tell me if u got any errors.

**Comment by Luckyhv** [comment]
According to your conversation it seems the env api urls are misconfigured

**Comment by Luckyhv** [comment]
yep i will check

**Comment by Luckyhv** [comment]
It works. The videos are playing fine.
