### ISSUE TITLE
Hey, sorry to bother you again. do you know why only gogo anime server is the only one showing? it also gives that error with the no episodes found and i keep having to refresh the page for them to show

### ISSUE THREAD

**Issue by InstaTechHD** [Luckyhv/aniplay#15]
Hey, sorry to bother you again. do you know why only gogo anime server is the only one showing? it also gives that error with the no episodes found and i keep having to refresh the page for them to show

_Originally posted by @InstaTechHD in https://github.com/Luckyhv/aniplay/issues/14#issuecomment-1987316404_

**Comment by Luckyhv** [comment]
Actually anify is currently down if it works Zoro will be available.
Maybe I should think other way to add Zoro
Also which anime is showing no episodes found

**Comment by Luckyhv** [comment]
Are u using the latest fork
My website shows other servers because they are already cached.
Wait I will check that link u posted

**Comment by Luckyhv** [comment]
I checked and the episodes are showing up I dont see any issue.
Join discord or DM me I will solve any issues as I can't check GitHub regularly

**Comment by Luckyhv** [comment]
Sure I'll look into it.

**Comment by Luckyhv** [comment]
Now look the episodes are shown. Hit that refresh icon right side to episodes and they show up if available
